env:
   node: true
   es2021: true

plugins:
- jest
overrides: []
extends: 
- 'airbnb-base'
- 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
 no-console: "off",
import/extentions: "off"
}